<?php

namespace WA\BoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ActorsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActorsRepository extends EntityRepository
{
    public function getAllActorsByNumber()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT COUNT(a.firstname) FROM WABoBundle:Actors a'
            )
            ->getSingleScalarResult();
    }
}
