<?php

namespace WA\BoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentsRepository extends EntityRepository
{
    public function getAllCommentsById()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT co FROM WABoBundle:Comments co ORDER BY co.id DESC'
            )
            ->getResult();
    }
}
