<?php

namespace WA\BoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TagsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagsRepository extends EntityRepository
{
    public function getTagsCloud()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT COUNT(t), t.word, t.id, tm.title FROM WABoBundle:Tags t
                JOIN t.movies tm
                GROUP BY t.word '
            )
            ->getResult();
    }
}
