directors:
    path:     /
    defaults: { _controller: "WABoBundle:Directors:index" }

directors_show:
    path:     /{id}/show
    defaults: { _controller: "WABoBundle:Directors:show" }

directors_new:
    path:     /new
    defaults: { _controller: "WABoBundle:Directors:new" }

directors_create:
    path:     /create
    defaults: { _controller: "WABoBundle:Directors:create" }
    requirements: { _method: post }

directors_edit:
    path:     /{id}/edit
    defaults: { _controller: "WABoBundle:Directors:edit" }

directors_update:
    path:     /{id}/update
    defaults: { _controller: "WABoBundle:Directors:update" }
    requirements: { _method: post|put }

directors_delete:
    path:     /{id}/delete
    defaults: { _controller: "WABoBundle:Directors:delete" }
    requirements: { _method: post|delete }
