tags:
    path:     /
    defaults: { _controller: "WABoBundle:Tags:index" }

tags_show:
    path:     /{id}/show
    defaults: { _controller: "WABoBundle:Tags:show" }

tags_new:
    path:     /new
    defaults: { _controller: "WABoBundle:Tags:new" }

tags_create:
    path:     /create
    defaults: { _controller: "WABoBundle:Tags:create" }
    requirements: { _method: post }

tags_edit:
    path:     /{id}/edit
    defaults: { _controller: "WABoBundle:Tags:edit" }

tags_update:
    path:     /{id}/update
    defaults: { _controller: "WABoBundle:Tags:update" }
    requirements: { _method: post|put }

tags_delete:
    path:     /{id}/delete
    defaults: { _controller: "WABoBundle:Tags:delete" }
    requirements: { _method: post|delete }
