imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
            - 'WABoBundle:layout:form.html.twig'

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [WABoBundle, WAFoBundle]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar"
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig     # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig # sort link template


fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: WA\BoBundle\Entity\User

#Elastic Search
fos_elastica:
    default_manager: orm
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        website:
            client: default
            index_name: website_qa
            types:
              movies:
                mappings:
                    typeFilm: { type: string }
                    title: { type: string }
                    synopsis: { type: string }
                    description: { type: string }
                    bo: { type: string }
                    annee: { type: string }
                    budget: { type: string }
                    duree: { type: string }
                    dateRelease: { type: string }
                    actors:
                      type: "nested"
                      properties:
                        lastname: { type: string }
                        firstname: { type: string }
                        city: { type: string }
                        biography: { type: string }
                        recompenses: { type: string }
                    cinemas:
                      type: "nested"
                      properties:
                        title: { type: string }
                        ville: { type: string }
                    directors:
                      type: "nested"
                      properties:
                        lastname: { type: string }
                        firstname: { type: string }
                        biography: { type: string }
                    moviesRelated:
                        type: "nested"
                        properties:
                          title: { type: string }
                          synopsis: { type: string }
                          description: { type: string }
                    tags:
                        type: "nested"
                        properties:
                          word: { type: string }
                persistence:
                    driver: orm
                    model: WA\BoBundle\Entity\Movies
                    repository: WA\BoBundle\Repository\MoviesRepository
                    provider:
                        query_builder_method: getActiveMoviesBuilder
                    finder: ~
                    listener: ~ # by default, listens to "insert", "update" and "delete"

# Lexik Paybox Bundle
lexik_paybox:
    servers:
      primary:
        system_path: '/cgi-bin/modulev500-RhE5-64bits.cgi'
    parameters:
        site:  '1999888'   # Site number provided by the bank
        rank:  '32'        # Rank number provided by the bank
        login: '110647233' # Customer's login provided by Paybox
        hmac:
            key: '0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF' # Key used to compute the hmac hash, provided by Paybox

