wa_fo:
    resource: "@WAFoBundle/Resources/config/routing.yml"
    prefix:   /


wa_bo:
    resource: "@WABoBundle/Resources/config/routing.yml"
    prefix:   /administration

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

# Lexik Paybox Bundle
lexik_paybox:
    resource: '@LexikPayboxBundle/Resources/config/routing.yml'

lexik_paybox_sample_return:
    resource: '@LexikPayboxBundle/Resources/config/routing_sample.yml'