security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_MEMBER: ROLE_MEMBER
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN


    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/administration
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                check_path: /administration/login_check
                login_path: /login
                default_target_path: /administration
                always_use_default_target_path: false
            logout:
                  path:   /administration/logout
                  target: /login
            anonymous:    true
        user:
           pattern: ^/
           form_login:
               provider: fos_userbundle
               csrf_provider: form.csrf_provider
               check_path: /user_login_check
               login_path: /user_login
               default_target_path: /home
               always_use_default_target_path: false
           logout:
                 path:   /user_logout
                 target: /home
           anonymous:    true


    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/administration/, role: ROLE_ADMIN }
        - { path: ^/user_login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }
