Categories:
    type: entity
    table: categories
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: true
            length: 250
            fixed: false
            comment: ''
        description:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
        slug:
            type: string
            nullable: true
            length: 300
            fixed: false
            comment: ''
        parentId:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: parent_id
        position:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
        lft:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
        lvl:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
        rgt:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
        root:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
        dateCreated:
            type: datetime
            nullable: true
            comment: ''
            column: date_created
        dateUpdated:
            type: datetime
            nullable: true
            comment: ''
            column: date_updated
    lifecycleCallbacks: {  }
