User:
    type: entity
    table: user
    uniqueConstraints:
        UNIQ_8D93D64992FC23A8:
            columns:
                - username_canonical
        UNIQ_8D93D649A0D96FBF:
            columns:
                - email_canonical
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        email:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
        username:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
        password:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
        ville:
            type: string
            nullable: true
            length: 200
            fixed: false
            comment: ''
        zipcode:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
        tel:
            type: string
            nullable: true
            length: 250
            fixed: false
            comment: ''
        ip:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: ''
        enabled:
            type: boolean
            nullable: true
            comment: ''
        lastLogin:
            type: datetime
            nullable: true
            comment: ''
            column: last_login
        expired:
            type: boolean
            nullable: true
            comment: ''
        locked:
            type: boolean
            nullable: true
            comment: ''
        usernameCanonical:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
            column: username_canonical
        emailCanonical:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
            column: email_canonical
        salt:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
        expiresAt:
            type: datetime
            nullable: true
            comment: ''
            column: expires_at
        confirmationToken:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
            column: confirmation_token
        passwordRequestedAt:
            type: datetime
            nullable: true
            comment: ''
            column: password_requested_at
        googleid:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
            column: googleId
        googleaccesstoken:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
            column: googleAccessToken
        flickrid:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
            column: flickrId
        flickraccesstoken:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
            column: flickrAccessToken
        githubid:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
            column: githubId
        githubaccesstoken:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
            column: githubAccessToken
        linkedinaccesstoken:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
            column: linkedinAccessToken
        linkedinid:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
            column: linkedinId
        roles:
            type: array
            nullable: true
            length: null
            fixed: false
            comment: ''
        extras:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
        longitude:
            type: float
            nullable: true
            precision: 10
            scale: 0
            comment: ''
        latitude:
            type: float
            nullable: true
            precision: 10
            scale: 0
            comment: ''
        facebookid:
            type: string
            nullable: true
            length: 300
            fixed: false
            comment: ''
            column: facebookId
        facebookaccesstoken:
            type: string
            nullable: true
            length: 300
            fixed: false
            comment: ''
            column: facebookAccessToken
        twitterid:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
            column: twitterId
        twitteraccesstoken:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
            column: twitterAccessToken
        credentialsExpired:
            type: boolean
            nullable: true
            comment: ''
            column: credentials_expired
        credentialsExpireAt:
            type: datetime
            nullable: true
            comment: ''
            column: credentials_expire_at
        createdAt:
            type: datetime
            nullable: true
            comment: ''
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            comment: ''
            column: updated_at
        deletedAt:
            type: datetime
            nullable: true
            comment: ''
            column: deleted_at
        lastactivity:
            type: datetime
            nullable: true
            comment: ''
            column: lastActivity
    manyToMany:
        movies:
            targetEntity: Movies
            cascade: {  }
            mappedBy: null
            inversedBy: user
            joinTable:
                name: user_favoris
                joinColumns:
                    -
                        name: user_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: movies_id
                        referencedColumnName: id
            orderBy: null
    lifecycleCallbacks: {  }
